import 'package:json_annotation/json_annotation.dart';

// This file will be generated by the build_runner.
// It connects this file to the generated code.
part 'user.g.dart';

// This annotation tells the generator to create serialization logic for this class.
@JsonSerializable()
class User {
  final String name;
  final String email;

  User(this.name, this.email);

  // Connects to the generated code for deserialization.
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  // Connects to the generated code for serialization.
  Map<String, dynamic> toJson() => _$UserToJson(this);
}